.TH "cutl::file_entity" 3 "common_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cutl::file_entity \- file entity struct\&. include file type and file path\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filetype\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfiletype\fP \fBtype\fP = { \fBfiletype::ft_unknown\fP }"
.br
.ti -1c
.RI "std::string \fBfilepath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
file entity struct\&. include file type and file path\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string cutl::file_entity::filepath"
file path 
.SS "\fBfiletype\fP cutl::file_entity::type = { \fBfiletype::ft_unknown\fP }"
file type 

.SH "Author"
.PP 
Generated automatically by Doxygen for common_util from the source code\&.
