.TH "cutl::timecount" 3 "Version 1.1.0" "common_util" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cutl::timecount \- A simple time counter class to measure the execution time of a function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timecount\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtimecount\fP (const std::string &func_name)"
.br
.RI "Construct a new timecount object The constructor will record the begin time of the function calling\&. "
.ti -1c
.RI "\fB~timecount\fP ()"
.br
.RI "Destroy the timecount object The desctructor will record the end time of the function calling and calculate the execution time\&. "
.in -1c
.SH "Detailed Description"
.PP 
A simple time counter class to measure the execution time of a function\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cutl::timecount::timecount (const std::string & func_name)"

.PP
Construct a new timecount object The constructor will record the begin time of the function calling\&. 
.PP
\fBParameters\fP
.RS 4
\fIfunc_name\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for common_util from the source code\&.
